api:
  unix_socket: /tmp/js8d.sock
  websocket_port: 0
audio:
  buffer_size: 1024
  input_channels: mono
  input_device: default
  notification_device: Built-in Output
  output_channels: mono
  output_device: default
  remember_power_tune: false
  remember_power_tx: false
  sample_rate: 48000
  save_directory: /Users/doug/Library/Application Support/JS8Call/save
hardware:
  enable_gpio: false
  enable_oled: false
  oled_height: 64
  oled_i2c_address: 0
  oled_width: 128
  ptt_gpio_pin: 18
  status_led_pin: 24
logging:
  compress: false
  console: false
  file: ""
  level: info
  max_age: 30
  max_backups: 5
  max_size: 100
  structured: false
radio:
  baud_rate: 115200
  civ_address: ""
  civ_transceive: false
  data_bits: default
  device: /dev/ttyUSB0
  dtr: default
  handshake: default
  mode: data
  model: "335"
  poll_interval: 1000
  ptt_command: ""
  ptt_method: cat
  ptt_port: ""
  rts: default
  split_operation: none
  stop_bits: default
  tx_audio_source: rear
  tx_delay: 0.2
  use_hamlib: true
station:
  callsign: K3DEP
  grid: FN20
storage:
  database_path: ""
  max_messages: 10000
web:
  bind_address: 0.0.0.0
  port: 8080
